In [1]:
import numpy as np
import pandas as pd
from sklearn import linear_model

df = pd.read_csv('NewJerseyHomePrices.csv')
df

Area  Bedroom  Age   Price
0  2600      3.0   20  550000
1  3000      4.0   15  565000
2  3200      NaN   18  610000
3  3600      3.0   30  595000
4  4000      5.0    8   76000
5  4100      6.0    8  810000

In [2]:
df.Bedroom.median()

4.0

In [4]:
df.Bedroom = df.Bedroom.fillna(df.Bedroom.median())
df

Area  Bedroom  Age   Price
0  2600      3.0   20  550000
1  3000      4.0   15  565000
2  3200      4.0   18  610000
3  3600      3.0   30  595000
4  4000      5.0    8   76000
5  4100      6.0    8  810000

In [5]:
reg = linear_model.LinearRegression()
reg.fit(df[['Area', 'Bedroom', 'Age']], df.Price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [7]:
reg.coef_

array([-7.04330154e+02,  7.61443120e+05,  7.92237276e+04])

In [8]:
reg.intercept_

-1539076.481561198

In [9]:
reg.predict([[3000, 3, 40]])

array([1801211.52321182])

In [11]:
reg.predict([[3500, 4, 15]])

array([229896.37567876])

In [12]:
nj_df = pd.read_csv('NewJerseyHousing.csv')
nj_df

Area  Bedroom  Age
0  3750        5   30
1  2100        3   15
2  3000        4   44
3  5400        6   10

In [13]:
newj = reg.predict(nj_df)
newj

array([2003612.87204235,  454515.47076905, 2879549.55404007,
         18436.68577384])

In [14]:
nj_df['Price'] = newj
nj_df

Area  Bedroom  Age         Price
0  3750        5   30  2.003613e+06
1  2100        3   15  4.545155e+05
2  3000        4   44  2.879550e+06
3  5400        6   10  1.843669e+04

In [15]:
nj_df.to_csv('NewJerseyHousePricePrediction.csv')